### ISSUE TITLE
awk  syntax error in run the  Montage.pl

### ISSUE THREAD

**Issue by heweihuang** [CAG-CNV/MONTAGE#1]
Error:
awk: cmd. line:8: sum=0;sum2=$;count=1;if($==lastChr){window+=slide}else{window=1000000};sumMid=0;sumLow=0;sumHig=0;sumHom=0;sumHomDel=0;start="";end="";if($>=0.4&&$<=0.6){sumMid++}else if($>=0.1&&$<0.4){sumLow++; if(start == ""){start=$} end=$}else if($>0.6&&$<=0.9){sumHig++; if(start == ""){start=$} end=$}else{sumHom++};sumBaf=$;sumsqBaf=($)^2;if($<-3){sumHomDel++}}

**Comment by heweihuang** [comment]
error:
awk: cmd. line:8: sum=0;sum2=$;count=1;if($==lastChr){window+=slide}else{window=1000000};sumMid=0;sumLow=0;sumHig=0;sumHom=0;sumHomDel=0;start="";end="";if($>=0.4&&$<=0.6){sumMid++}else if($>=0.1&&$<0.4){sumLow++; if(start == ""){start=$} end=$}else if($>0.6&&$<=0.9){sumHig++; if(start == ""){start=$} end=$}else{sumHom++};sumBaf=$;sumsqBaf=($)^2;if($<-3){sumHomDel++}}

**Comment by joeglessner1** [comment]
Is there a header on your input BAF/LRR signal files? Check the output logfile *_Montage.log for a line starting with "Indexes: " or with "ERROR" preceding the error you posted. Header must be present in the format *.Log R Ratio or *.LRR in a column and *.B Allele Freq or *.BAF  in another column.
